# Generated by Django 3.0.6 on 2020-06-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=80)),
                ('subject', models.CharField(max_length=254)),
                ('message', models.TextField()),
                ('delay', models.PositiveSmallIntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
